watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 8
      left: 8
      bottom: 0
      right: 8
    widgets:
      left:
      - "home"
      - "komorebi_control"
      - "komorebi_workspaces"
      center:
      - "clock"
      right:
      - "media"
      - "weather"
      - "volume"
      - "notifications"
      - "power_menu"
widgets:
  komorebi_control:
    type: "komorebi.control.KomorebiControlWidget"
    options:
      label: "<span>\udb80\uddd9</span>"
      icons:
        start: "\uead3"
        stop: "\uead7"
        reload: "\uead2"
      run_ahk: false
      run_whkd: true
      show_version: true
      komorebi_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "~/Downloads" }
        - { title: "Documents", path: "~/Documents" }
        - { title: "Pictures", path: "~/Pictures" }
      system_menu: true
      power_menu: true
      offset_left: -6
      blur: true
      round_corners: true
      border_color: None
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "\uf001 {title}"
      label_alt: "\uf001 {artist}"
      max_field_size:
        label: 40
        label_alt: 24
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      callbacks:
        on_left: "toggle_play_pause"
        on_middle: "toggle_label"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\ue0ba</span>{%H:%M}<span>\ue0bc</span>"
      label_alt: "<span>\ue0ba</span>{%A, %d %B %Y}<span>\ue0bc</span>"
      callbacks:
        on_left: "toggle_calendar"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        offset_left: 0
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "\udb81\ude40 Tiling"
        floating_label: "\udb80\udd37 Floating"
      animation: true
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>\udb81\udd99</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: env
      update_interval: 120
      hide_decimal: true
      units: "metric"
      location: env
      show_alerts: true
      callbacks:
        on_left: "toggle_card"
        on_middle: "toggle_label"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "right"
        direction: "down"
        icon_size: 32
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{level}"
      tooltip: false
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: 'right'
        direction: 'down'
      callbacks:
        on_middle: "toggle_label"
        on_right: "toggle_mute"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["\udb81\udf3a", "Cancel"]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
