watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop; komorebic start"
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    animation:
      enabled: true
      duration: 500
    widgets:
      left: [
          "home",
          "wallpapers",
          "komorebi_workspaces",
          "komorebi_active_layout",
          "whkd",
          "active_window",
        ]
      center: [
          "clock"
        ]
      right: [
          "systray",
          "media",
          "language",
          "obs",
          "volume",
          "microphone",
          "wifi",
          "battery",
          "apps",
          "update_check",
          "notifications",
          "power_menu",
        ]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "   "
      label_alt: "{title}"
      max_field_size:
        label: 12
        label_alt: 10
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 250
      thumbnail_padding: 0
      thumbnail_corner_radius: 6
      thumbnail_edge_fade: false
      symmetric_corner_radius: true
      icons:
        play: ""
        pause: ""
        prev_track: ""
        next_track: ""
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "toggle_label"
        on_right: "toggle_play_pause"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 0
        offset_left: 0
        thumbnail_corner_radius: 12
        thumbnail_size: 100
        max_title_size: 100
        max_artist_size: 40
        show_source: true
      media_menu_icons:
        play: ""
        pause: ""
        prev_track: ""
        next_track: ""
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "{win[process][name]}" # {win[class_name]} {win[hwnd]}
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true
      callbacks:
        on_left: 'toggle_label'
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a. %H:%M}"
      label_alt: "{%a %d. %b  %I:%M %p}"
      locale: 'en_EN'
      timezones: []
      calendar: 
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "System"
        offset_top: 0
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: 'toggle_calendar'
        on_middle: 'toggle_label'
        on_right: "do_nothing"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      label_default_name: ""
      label_float_override: "Float"
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: true
      animation: false
      toggle_workspace_layer:
        enabled: false
        tiling_label: "\udb81\ude40"
        floating_label: "\uf2d2"
      app_icons: 
        enabled_populated: true
        enabled_active: false
        size: 16
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximised: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: "prev_layout"
        on_middle: "toggle_monocle"
        on_right: "next_layout"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {level}"
      volume_icons:
        - ""  # Icon for muted
        - ""  # Icon for 0-10% volume
        - ""  # Icon for 11-30% volume
        - ""  # Icon for 31-60% volume
        - ""  # Icon for 61-100% volume
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
        on_middle: "toggle_label"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: 'small'
        border_color: 'System'
        offset_top: 0
        alignment: 'center'
        direction: 'down'
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {level}"
      icons:
        normal: ""
        muted: ""
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {percent}%"
      update_interval: 1000
      time_remaining_natural: true
      charging_options:
        icon_format: "{charging_icon}"
      status_icons: 
        icon_charging: ""
        icon_critical: ""
        icon_low: ""
        icon_medium: ""
        icon_high: ""
        icon_full: ""
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:powersleep"
        on_middle: "toggle_label"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: ""
      uptime: true
      blur: true
      blur_background: true
      animation_duration: 200 # Milisecond
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\ue72e", "Lock"]
        sleep: ["\u23fe","Sleep"]
        restart: ["\ue777", "Restart"]
        shutdown: ["\ue7e8", "Shut down"]
        cancel: ["\ue711", "Cancel"]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      image_icon_size: 14
      app_list:
        - { icon: "\ue690", launch: "quick_settings" }
  wallpapers:  
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span></span>"
      image_path: "$env:USERPROFILE/Downloads/Pictures"
      change_automatically: false
      update_interval: 600 # in seconds
      gallery:
        enabled: true
        blur: true
        image_width: 280
        image_per_page: 6
        show_buttons: false # up and down arrow keys to switch new or previous pages
        orientation: "portrait"
        image_spacing: 25
        lazy_load: true
        lazy_load_delay: 40
        lazy_load_fadein: 200
        image_corner_radius: 40
        enable_cache: true
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-20% strength
          "\udb82\udd22", # Icon for 21-40% strength
          "\udb82\udd25", # Icon for 41-80% strength
          "\udb82\udd28", # Icon for 81-100% strength
        ]
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span> {ip_addr}"
      ethernet_icon: ""
      callbacks:
        on_left: "exec cmd.exe /c start ms-availablenetworks:"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: ""
      special_keys:
        - key: "win"
          key_replace: "\ue70f"
        - key: "ctrl"
          key_replace: "Ctrl"
        - key: "alt" 
          key_replace: "Alt"
        - key: "shift"
          key_replace: "Shift"
        - key: "left"
          key_replace: "\u2190"
        - key: "right"
          key_replace: "\u2192"
        - key: "up"
          key_replace: "\u2191"
        - key: "down"
          key_replace: "\u2193"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      windows_update:
        enabled: false
        label: "<span>󰚰</span> {count}"
        interval: 60
        exclude: []
      winget_update:
        enabled: true
        label: "<span></span> {count}"
        tooltip: true
        interval: 30 # in minutes
        exclude: []
  obs:
    type: "yasb.obs.ObsWidget"
    options:
      connection: # WebSocket Server Settings
        host: "192.168.18.125" 
        port: 4455
        password: "HV1FfGAGDrhKdAbQ"
      icons:
        recording: ""
        stopped: ""
        paused: ""
      hide_when_not_recording: true
      blinking_icon: true
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span></span>{lang[country_code]}"
      label_alt: "{lang[native_lang_name]}"
      update_interval: 1
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "exec cmd /c nircmd sendkeypress 0x5B+0x20"
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span></span>"
      menu_list:
      - { title: "Useprofile", path: "~" }
      - { title: "Downloads", path: "~/Downloads" }
      - { title: "Documents", path: "~/Documents" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "small"
      border_color: "System"
      offset_top: 0
      offset_left: 0
      alignment: "center"
      direction: "down"
      container_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span></span> {count}"
      label_alt: "{count} notifications"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: ""
      label_expanded: ""
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      unpinned_vis_btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
